import "./style.css";
import { Level } from "./components/Level";

export function Test() {
  return (
    <>
      <div>
        <h1>Algo-Structures</h1>
        <div className="title">Algorithms</div>
        <div className="gallery">
          <ul
            style={{
              width: "120px",
              height: "80px",
            }}
          >
            <li
              style={{
                backgroundImage:
                  'url("https://static.javatpoint.com/tutorial/daa/images/daa-merge-sort.png")',
              }}
            >
              A
            </li>
            <li
              style={{
                backgroundImage:
                  'url("https://static.javatpoint.com/tutorial/daa/images/daa-merge-sort.png")',
              }}
            >
              A
            </li>
            <li
              style={{
                backgroundImage:
                  'url("https://static.javatpoint.com/tutorial/daa/images/daa-merge-sort.png")',
              }}
            >
              A
            </li>
            <li
              style={{
                backgroundImage:
                  'url("https://static.javatpoint.com/tutorial/daa/images/daa-merge-sort.png")',
              }}
            >
              A
            </li>
            <li
              style={{
                backgroundImage:
                  'url("https://static.javatpoint.com/tutorial/daa/images/daa-merge-sort.png")',
              }}
            >
              A
            </li>
            <li
              style={{
                backgroundImage:
                  'url("https://static.javatpoint.com/tutorial/daa/images/daa-merge-sort.png")',
              }}
            >
              A
            </li>
            <li
              style={{
                backgroundImage:
                  'url("https://static.javatpoint.com/tutorial/daa/images/daa-merge-sort.png")',
              }}
            >
              A
            </li>
            <li
              style={{
                backgroundImage:
                  'url("https://static.javatpoint.com/tutorial/daa/images/daa-merge-sort.png")',
              }}
            >
              A
            </li>
            <li
              style={{
                backgroundImage:
                  'url("https://static.javatpoint.com/tutorial/daa/images/daa-merge-sort.png")',
              }}
            >
              A
            </li>
          </ul>
          <Level
            name="MergeSort"
            img="https://static.javatpoint.com/tutorial/daa/images/daa-merge-sort.png"
          />
          <ul>
            <li>A</li>
            <li>B</li>
            <li>C</li>
            <li>D</li>
            <li>E</li>
            <li>6</li>
            <li>7</li>
            <li>8</li>
            <li>9</li>
          </ul>
          <ul>
            <li>A</li>
            <li>B</li>
            <li>C</li>
            <li>D</li>
            <li>E</li>
            <li>6</li>
            <li>7</li>
            <li>8</li>
            <li>9</li>
          </ul>
          <ul>
            <li>A</li>
            <li>B</li>
            <li>C</li>
            <li>D</li>
            <li>E</li>
            <li>6</li>
            <li>7</li>
            <li>8</li>
            <li>9</li>
          </ul>
          <ul>
            <li>A</li>
            <li>B</li>
            <li>C</li>
            <li>D</li>
            <li>E</li>
            <li>6</li>
            <li>7</li>
            <li>8</li>
            <li>9</li>
          </ul>
          <ul>
            <li>A</li>
            <li>B</li>
            <li>C</li>
            <li>D</li>
            <li>E</li>
            <li>6</li>
            <li>7</li>
            <li>8</li>
            <li>9</li>
          </ul>
          <ul>
            <li>A</li>
            <li>B</li>
            <li>C</li>
            <li>D</li>
            <li>E</li>
            <li>6</li>
            <li>7</li>
            <li>8</li>
            <li>9</li>
          </ul>
          <ul>
            <li>A</li>
            <li>B</li>
            <li>C</li>
            <li>D</li>
            <li>E</li>
            <li>6</li>
            <li>7</li>
            <li>8</li>
            <li>9</li>
          </ul>
          <ul>
            <li>A</li>
            <li>B</li>
            <li>C</li>
            <li>D</li>
            <li>E</li>
            <li>6</li>
            <li>7</li>
            <li>8</li>
            <li>9</li>
          </ul>
          <ul>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
          </ul>
        </div>
      </div>
    </>
  );
}
